name: deploy prod

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: prod
      cancel-in-progress: true
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          # hostname / IP of the server
          host: ${{ secrets.PROD_SSH_HOST }}
          port: ${{secrets.PROD_SSH_PORT}}
          user: ${{ secrets.PROD_SSH_USERNAME }}
          private_key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          host_fingerprint: ${{ secrets.PROD_SSH_FINGERPRINT }}
          command: source ~/.nvm/nvm.sh; ~/www/deploy-scripts/my-courses-frontend.sh
